### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Stories index
GET http://localhost:3000/stories.json
Content-Type: application/json

### Stories create
POST http://localhost:3000/stories
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzU4MDA0NjB9.gQk-DMuVF4xVYiDUAobo_5YDAYndXPq94C34wP8r4WI
Content-Type: application/json

{
  "title": "My story",
  "graph": {
		"start": "It all begins here..."
	}
}

### Stories show
GET http://localhost:3000/stories/2.json
Content-Type: application/json

### Stories update
PATCH http://localhost:3000/stories/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzU4MDA0NjB9.gQk-DMuVF4xVYiDUAobo_5YDAYndXPq94C34wP8r4WI
Content-Type: application/json

{
  "title": "My updated story",
  "graph": {
		"start": "It all begins here...",
    "journey": "The adventure begins."
	}
}

### Stories destroy
DELETE http://localhost:3000/stories/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzU4MDA0NjB9.gQk-DMuVF4xVYiDUAobo_5YDAYndXPq94C34wP8r4WI
Content-Type: application/json