### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Stories index
GET http://localhost:3000/stories.json
Content-Type: application/json

### Stories index
GET http://localhost:3000/stories/1.json
Content-Type: application/json